[application]
name = "course_pilot"
default_platform = "desktop"

[desktop]
enable_hotreload = true

[bundle]
identifier = "com.k5602.course_pilot"
name = "Course Pilot"
publisher = "Archer"
icons = [
    "assets/icons/icon.png",
    "assets/icons/32x32.png",
    "assets/icons/128x128.png",
    "assets/icons/256x256.png",
    "assets/icons/512x512.png",
    "assets/icons/icon.ico"
]

[bundle.linux]
bin_artifacts = ["deb"]
strip = true

[web.resources]
csp = "default-src 'self'; frame-src 'self' https://*.youtube.com https://www.youtube.com"
